### ISSUE TITLE
.gitattributes: two rules are inert, *.md has no eol rule, 38 files stored CRLF

### ISSUE THREAD

**Issue by laywill** [laywill/awesome-claude-code-subagents#308]
Found while reviewing `.gitattributes` after the CRLF failure in #303.

## 1. `chmod=+x` and `chmod=640` do nothing

```
*.sh chmod=+x
*.md chmod=640
```

**Git has no `chmod` attribute.** `.gitattributes` cannot set file modes — the executable bit is stored in the index (`100644` vs `100755`). These two lines have never had any effect.

They look functional because `git check-attr chmod -- install-agents.sh` prints `chmod: +x`. That is misleading: `check-attr` echoes back any key you invent, including ones Git does not implement.

Proof on `main`:

```
100755  install-agents.sh
100644  tools/subagent-catalog/config.sh   <- matches *.sh chmod=+x, not executable
```

`scripts/validate-catalog.sh` (added in #303) was likewise created `100644` and only became executable via an explicit `git update-index --chmod=+x`. Nothing in the repository reads these attributes.

`640` is doubly meaningless — Git only ever records 644 or 755.

## 2. `*.md` has no `eol` rule

Markdown is 236 of 267 tracked files and is the repository's actual source, parsed by tooling. It is covered only by `* text=auto`.

This is the gap the #303 CI failure came through: 38 agent files are stored with CRLF, and `awk` under mawk read every frontmatter value back as empty.

`*.json` (26 files, all currently LF) is unpinned for the same reason.

## 3. `git add --renormalize` cannot fix this as configured

Running it today changes **0 files**, despite the 38 CRLF blobs. `text=auto` deliberately leaves files alone that already have CRLF in the index, to avoid churning history. The setting meant to prevent the problem is what preserves it.

With `*.md text eol=lf` added, the same command converts exactly those 38 files. `git diff -w --numstat` reports `0 0` for every one — line endings only, no content change.

## 4. Dead rules

`*.bat`, `*.cmd`, `*.ics` and their uppercase variants have never existed in this repository's history (checked with `git log --all --diff-filter=A`).

`*.ps1`, `*.psm1`, `*.psd1` have not either, but are worth keeping: a PowerShell counterpart to `install-agents.sh` is plausible, and the preemptive `*.yml` rule proved its worth when #303 added the first workflow.

## Proposed fix

- add `*.md text eol=lf` and `*.json text eol=lf`
- remove the two `chmod` lines, replaced by a comment explaining the real mechanism
- drop the `bat`/`cmd`/`ics` rules, keep the PowerShell ones
- `git add --renormalize .` to convert the 38 files
- document `git update-index --chmod=+x` in CLAUDE.md so the next script does not land non-executable

## Out of scope, but noticed

`.claude/settings.local.json` is tracked. A `.local.json` is conventionally per-developer and gitignored; `.gitignore` says nothing about it. May be deliberate.
